[package]
name = "op-proposer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-tracing.workspace = true

alloy-primitives.workspace = true
alloy-sol-types = { workspace = true, features = ["json"] }
alloy-signer-wallet.workspace = true
alloy-network.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true
alloy-contract.workspace = true

tokio.workspace = true
futures.workspace = true

eyre.workspace = true
serde = { workspace = true, features = ["derive"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
config = "0.14.0"
parking_lot.workspace = true